### ISSUE TITLE
I copy this to test,but it doesn't work

### ISSUE THREAD

**Issue by yaj52125** [DevExpress-Examples/how-to-show-a-tooltip-for-a-comboboxedit-item-e1334#1]
in my case,
**I use DevExpress.XtraVerticalGrid.VGridControl and 
add a item DevExpress.XtraEditors.Repository.RepositoryItemComboBox,,**

use Example Code,
PopupListBoxForm form = (sender as IPopupControl).PopupWindow as PopupListBoxForm;
form.ListBox.MouseMove += ListBox_MouseMove;
form.ListBox.MouseLeave += ListBox_MouseLeave;

**form is null**  
 
how should I do?

thanks

**Comment by LexEPoX** [comment]
Hello,

I checked this scenario with the latest version of our controls (currently, it is 18.2.3) and it works as expected. I recorded a [video](https://github.com/DevExpress-Examples/how-to-show-a-tooltip-for-a-comboboxedit-item-e1334/files/2629875/E1334-Issie-1-video.zip) to illustrate this. If you use the same approach, but the issue still occurs, the best way to proceed is to create a new ticket in our [Support Center](https://devexpress.com/ask). Attach a sample demonstrating the problematic behavior to that ticket and we will be happy to assist you.

**Comment by yaj52125** [comment]
thanks for your reply,I will take you advise
I am now using 14.2 version

**Comment by LexEPoX** [comment]
You are welcome.

P.S. I have additionally checked the same sample with version 14.2.3 and 14.2.15. In both cases, tooltips are shown as expected. If you still face the issue, we will do our best to provide you with a solution in our [Support Center](https://devexpress.com/ask).
